#!/bin/env bash

# create timescale
docker run -d \
  --name=timescale \
  -p 127.0.0.1:5433:5432 \
  -e POSTGRES_PASSWORD=postgres \
  timescale/timescaledb:latest-pg13

# create postgres
docker run -d \
  --name=postgres \
  -p 127.0.0.1:5434:5432 \
  -e POSTGRES_PASSWORD=postgres \
  -v "$PWD/scripts/postgres.conf":/etc/postgresql/postgresql.conf \
  postgres:alpine \
  -c config_file=/etc/postgresql/postgresql.conf
