#!/bin/env bash
# for controlling testing infra

function createPG {
  docker run -d \
    --name=postgres \
    -p 127.0.0.1:5434:5432 \
    -e POSTGRES_PASSWORD=postgres \
    -v "$PWD/scripts/postgres.conf":/etc/postgresql/postgresql.conf \
    postgres:alpine \
    -c config_file=/etc/postgresql/postgresql.conf
}

function createTS {
  docker run -d \
    --name=timescale \
    -p 127.0.0.1:5433:5432 \
    -e POSTGRES_PASSWORD=postgres \
    timescale/timescaledb:latest-pg13
}

function destroyPG {
  docker stop postgres
  docker rm postgres
}

function destroyTS {
  docker stop timescale
  docker rm timescale
}

case $1 in
"create")
  case $2 in
  "pg")
    createPG
    ;;
  "ts")
    createTS
    ;;
  "all")
    createPG
    createTS
    ;;
  "-h" | "--help")
    echo "Usage : ctl create pg|ts|all"
    exit 1
    ;;
  esac
  ;;
"destroy")
  case $2 in
  "pg")
    destroyPG
    ;;
  "ts")
    destroyTS
    ;;
  "all")
    destroyPG
    destroyTS
    ;;
  "-h" | "--help")
    echo "Usage : ctl destroy pg|ts|all"
    exit 1
    ;;
  esac
  ;;

"-h" | "--help")
  echo "Usage : ctl create|destroy pg|ts|all"
  exit 1
  ;;
esac
