#!/bin/env bash
# load test with wrk

# set ulimit to 10M
ulimit -n 1000000

case $1 in
"create")
  wrk -t80 -d10s -c400 -s "$PWD/scripts/put.lua" http://localhost:5000/api/v1/links
  ;;
"get")
  wrk -t80 -d10s -c400 http://localhost:5000/$2
  ;;
"api")
  wrk -t80 -d10s -c400 http://localhost:5000/api/v1/links/$2
  ;;
"-h" | "--help")
  echo "Usage : load create|get|api <link>"
  exit 1
  ;;
esac
